### PR TITLE
Expense Tracker

### PR DESCRIPTION
**Pull request by rohanBagchi**
I have made an amateurish attempt at implementing an expense tracker as per your specification using ember js. Please review  and get back to me.

### CODE REVIEW

**Comment by rohanBagchi** [comment]
minor refactoring

**Comment by rohanBagchi** [comment]
Refactoring done. App is now live at [link to BountyExpenseTracker](https://artooexpensetracker.firebaseapp.com/)

**Comment by sameersegal** [comment]
Interesting work @rohanBagchi. Quick feedback:
* You should show settlement across all the transactions; not just per transaction. E.g Dev1,Dev2,Dev3 have done a few transactions. Cumulatively, Dev3 needs to pay 11k to Dev1 and 15k to Dev2 since Dev1 also owes money to Dev2

Others @shubhamR2 @kushdilip @kaushikbhat @shrivatsas feel free to give feedback.

**Comment by rohanBagchi** [comment]
@sameersegal I have attempted at addresing your review comment. App is live at [link to BountyExpenseTracker](https://artooexpensetracker.firebaseapp.com/)

**Comment by sameersegal** [comment]
Nice! Any test cases?

--
Sameer Segal, Founder & CEO, *Artoo | *+91-98866-89754 <+919886689754> /
+91-80-3301-3059

**Comment by rohanBagchi** [comment]
I will have to go through unit testing emberJs in the guides to write one. I will make an attempt.

**Comment by kaushikbhat** [comment]
@rohanBagchi - This is very well done - I like it. You have made best use of Ember's conventions and best practices. The UX is neat and intuitive. 

-  As a bonus would it be possible to add a download feature on the settlements or transactions table? Just a simple .csv download 
-  Also, you have imported each .js file separately. Use require.js maybe? Ember-CLI does this automatically for you.

**Comment by rohanBagchi** [comment]
@kaushikbhat : Thanks :)
I will attempt doing the CSV download tonight.
The requireJs part, I have to study. Yes, Ember CLI does it automatically,
but it needs ember latest with ES6 module syntax, which it then transpiles
to ES5 and in the process, converts ES6 modules to ES5 requirejs modules. I
began work in that path, but my laptop is an old machine and on every
change, when the system had to build the project, it overwhelmed my once
great machine. So I used ember 1.10 where everything is attached to the
global namespace. There was no more continuous build and I could work with
ease. That said, I will go try using requireJs modules with 1.10.

On Wed, 17 Jun 2015 at 09:07 Kaushik Bhat <notifications@github.com> wrote:

> @rohanBagchi <https://github.com/rohanBagchi> - This is very well done -
> I like it. You have made best use of Ember's conventions and best
> practices. The UX is neat and intuitive.
>
>    - As a bonus would it be possible to add a download feature on the
>    settlements or transactions table? Just a simple .csv download
>    - Also, you have imported each .js file separately. Use require.js
>    maybe? Ember-CLI does this automatically for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArtooTrills/Bounty-Web-Expenses/pull/5#issuecomment-112641613>
> .
>
-- 

Regards,
Rohan Bagchi

**Comment by rohanBagchi** [comment]
@kaushikbhat I implemented export to csv for expenses and settlements. Using ember with requireJs however, I have to go through. Had I used ember CLI, it would have been done automatically. But I had to use ember 1.10.
As for the testing, @sameersegal I have never used qunit. It will take me some time to write my 1st test case. 
That said, is it possible to process my submission as is, as in, without the test cases and requireJs modules?

**Comment by sameersegal** [comment]
Let's do them in parallel. When can you come over?

Best, Sameer

**Comment by rohanBagchi** [comment]
Hey Sameer,
will it be possible to do the same in skype?

On Wed, 17 Jun 2015 at 22:28 Sameer Segal <notifications@github.com> wrote:

> Let's do them in parallel. When can you come over?
>
> Best, Sameer
> On 17-Jun-2015 10:25 pm, "Rohan Bagchi" <notifications@github.com> wrote:
>
> > @kaushikbhat <https://github.com/kaushikbhat> I implemented export to
> csv
> > for expenses and settlements. Using ember with requireJs however, I have
> to
> > go through. Had I used ember CLI, it would have been done automatically.
> > But I had to use ember 1.10.
> > As for the testing, @sameersegal <https://github.com/sameersegal> I have
> > never used qunit. It will take me some time to write my 1st test case.
> > That said, is it possible to process my submission as is, as in, without
> > the test cases and requireJs modules?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ArtooTrills/Bounty-Web-Expenses/pull/5#issuecomment-112875677
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArtooTrills/Bounty-Web-Expenses/pull/5#issuecomment-112876785>
> .
>
-- 

Regards,
Rohan Bagchi

**Comment by rohanBagchi** [comment]
@sameersegal just to clarify, I suggested skype as it would be a very cost effective solution for now. I personally have no issues in coming over to your office as long as my travel and accommodation are taken care of.

**Comment by sameersegal** [comment]
Rohan, where are you based?

--
Sameer Segal, Founder & CEO, *Artoo | *+91-98866-89754 <+919886689754> /
+91-80-3301-3059

**Comment by rohanBagchi** [comment]
Hello Sameer,
I am from Kolkata.

On Thu, 18 Jun 2015 at 21:59 Sameer Segal <notifications@github.com> wrote:

> Rohan, where are you based?
>
> --
> Sameer Segal, Founder & CEO, *Artoo | *+91-98866-89754 <+919886689754> /
> +91-80-3301-3059
>
>
> On Wed, Jun 17, 2015 at 11:16 PM, Rohan Bagchi <notifications@github.com>
> wrote:
>
> > Hey Sameer,
> > will it be possible to do the same in skype?
> >
> > On Wed, 17 Jun 2015 at 22:28 Sameer Segal <notifications@github.com>
> > wrote:
> >
> > > Let's do them in parallel. When can you come over?
> > >
> > > Best, Sameer
> > > On 17-Jun-2015 10:25 pm, "Rohan Bagchi" <notifications@github.com>
> > wrote:
> > >
> > > > @kaushikbhat <https://github.com/kaushikbhat> I implemented export
> to
> > > csv
> > > > for expenses and settlements. Using ember with requireJs however, I
> > have
> > > to
> > > > go through. Had I used ember CLI, it would have been done
> > automatically.
> > > > But I had to use ember 1.10.
> > > > As for the testing, @sameersegal <https://github.com/sameersegal> I
> > have
> > > > never used qunit. It will take me some time to write my 1st test
> case.
> > > > That said, is it possible to process my submission as is, as in,
> > without
> > > > the test cases and requireJs modules?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/ArtooTrills/Bounty-Web-Expenses/pull/5#issuecomment-112875677
> > > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/ArtooTrills/Bounty-Web-Expenses/pull/5#issuecomment-112876785
> > >
> > > .
> > >
> > --
> >
> > Regards,
> > Rohan Bagchi
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ArtooTrills/Bounty-Web-Expenses/pull/5#issuecomment-112889307
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArtooTrills/Bounty-Web-Expenses/pull/5#issuecomment-113209879>
> .
>
-- 

Regards,
Rohan Bagchi

**Comment by sameersegal** [comment]
Ok, let's do a call on Saturday? Is everyone available at 11am on Sat?

--
Sameer Segal, Founder & CEO, *Artoo | *+91-98866-89754 <+919886689754> /
+91-80-3301-3059

**Comment by rohanBagchi** [comment]
I am available this saturday.

On Thu, 18 Jun 2015 at 22:03 Sameer Segal <notifications@github.com> wrote:

> Ok, let's do a call on Saturday? Is everyone available at 11am on Sat?
>
> --
> Sameer Segal, Founder & CEO, *Artoo | *+91-98866-89754 <+919886689754> /
> +91-80-3301-3059
>
>
> On Thu, Jun 18, 2015 at 10:01 PM, Rohan Bagchi <notifications@github.com>
> wrote:
>
> > Hello Sameer,
> > I am from Kolkata.
> >
> > On Thu, 18 Jun 2015 at 21:59 Sameer Segal <notifications@github.com>
> > wrote:
> >
> > > Rohan, where are you based?
> > >
> > > --
> > > Sameer Segal, Founder & CEO, *Artoo | *+91-98866-89754 <+919886689754>
> /
> >
> > > +91-80-3301-3059
> > >
> > >
> > > On Wed, Jun 17, 2015 at 11:16 PM, Rohan Bagchi <
> notifications@github.com
> > >
> > > wrote:
> > >
> > > > Hey Sameer,
> > > > will it be possible to do the same in skype?
> > > >
> > > > On Wed, 17 Jun 2015 at 22:28 Sameer Segal <notifications@github.com>
> > > > wrote:
> > > >
> > > > > Let's do them in parallel. When can you come over?
> > > > >
> > > > > Best, Sameer
> > > > > On 17-Jun-2015 10:25 pm, "Rohan Bagchi" <notifications@github.com>
> > > > wrote:
> > > > >
> > > > > > @kaushikbhat <https://github.com/kaushikbhat> I implemented
> export
> > > to
> > > > > csv
> > > > > > for expenses and settlements. Using ember with requireJs
> however, I
> > > > have
> > > > > to
> > > > > > go through. Had I used ember CLI, it would have been done
> > > > automatically.
> > > > > > But I had to use ember 1.10.
> > > > > > As for the testing, @sameersegal <https://github.com/sameersegal
> >
> > I
> > > > have
> > > > > > never used qunit. It will take me some time to write my 1st test
> > > case.
> > > > > > That said, is it possible to process my submission as is, as in,
> > > > without
> > > > > > the test cases and requireJs modules?
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > > >
> > > >
> > >
> >
> https://github.com/ArtooTrills/Bounty-Web-Expenses/pull/5#issuecomment-112875677
> > > > > >
> > > > > > .
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > >
> > >
> >
> https://github.com/ArtooTrills/Bounty-Web-Expenses/pull/5#issuecomment-112876785
> > > > >
> > > > > .
> > > > >
> > > > --
> > > >
> > > > Regards,
> > > > Rohan Bagchi
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/ArtooTrills/Bounty-Web-Expenses/pull/5#issuecomment-112889307
> > > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/ArtooTrills/Bounty-Web-Expenses/pull/5#issuecomment-113209879
> > >
> > > .
> > >
> > --
> >
> > Regards,
> > Rohan Bagchi
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ArtooTrills/Bounty-Web-Expenses/pull/5#issuecomment-113210634
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArtooTrills/Bounty-Web-Expenses/pull/5#issuecomment-113211276>
> .
>
-- 

Regards,
Rohan Bagchi

**Comment by kushdilip** [comment]
I am available till 12.30 pm.

Dilip Kushwaha, Geek
Artoo IT Solutions Pvt Ltd
www.artoo.in

**Pull request closed without merging**
